name: Build and Push to AWS ECR

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t kwvt:${{ github.sha }} -f ./Dockerfile .

      - name: Configure GitHub Credentials
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Run Docker Scout vulnerability analysis
        uses: docker/scout-action@v1 # Use the official action
        with:
          image: kwvt:${{ github.sha }}
          command: cves
          # Fail the action if critical or high severity issues with a fix are found
          only-fixed: true
          exit-code: true
          # Specify severity thresholds
          only-severity: critical,high

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker Image
        run: |
          docker tag kwvt:${{ github.sha }} \
          899740821150.dkr.ecr.$AWS_REGION.amazonaws.com/kwvt:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push 899740821150.dkr.ecr.$AWS_REGION.amazonaws.com/kwvt:${{ github.sha }}
