name: Build and Push to AWS ECR

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t kwvt:${{ github.sha }} -f ./Dockerfile .

      - name: Install Docker Scout
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b /usr/local/bin
          docker-scout version

      - name: Scan image with Docker Scout
        run: |
          docker-scout cves kwvt:${{ github.sha }} --severity CRITICAL > scout-output.txt || true
          cat scout-output.txt

      - name: Fail on Critical CVE
        run: |
          if grep -q "CRITICAL" scout-output.txt; then
            echo "Critical CVE found! Failing workflow."
            exit 1
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker Image
        run: |
          docker tag kwvt:${{ github.sha }} \
          899740821150.dkr.ecr.$AWS_REGION.amazonaws.com/kwvt:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push 899740821150.dkr.ecr.$AWS_REGION.amazonaws.com/kwvt:${{ github.sha }}
